# Generated by Django 6.0.5 on 2026-05-07 09:46

import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid_upfront', 'Paid Upfront (No Due)'), ('payment_due', 'Payment After Service (Due Date Required)'), ('partially_paid', 'Partially Paid (Due Date Required)'), ('already_paid', 'Already Paid (No Due)'), ('due_paid', 'Previously Due, Now Paid (No Due)')], default='payment_due', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='year',
            field=models.PositiveIntegerField(default=invoices.models.current_year, editable=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
