# Generated by Django 6.0.5 on 2026-05-10 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_invoice_no_invoice_status_invoice_suffix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='special_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
