# Generated by Django 6.0.5 on 2026-05-13 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_image_invoice_special_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='context_title',
            field=models.CharField(blank=True, help_text='Specific subject (e.g., Machine Name, Project Code, or Service Type)', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='header_style',
            field=models.CharField(choices=[('LEFT', 'Left Aligned'), ('CENTER', 'Centered'), ('RIGHT', 'Right Aligned')], default='CENTER', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='InvoiceLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_label_title', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoicelabel'),
        ),
    ]
