# Generated by Django 6.0.5 on 2026-06-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_theme_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('payment_due', 'Payment After Service'), ('partially_paid', 'Partially Paid'), ('due_paid', 'Previously Due, Now Paid')], default='payment_due', max_length=20),
        ),
    ]
