# Generated by Django 6.0.5 on 2026-06-05 11:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('system_type', models.CharField(choices=[('SEASONAL', 'Seasonal / Festival Campaign'), ('COUPON', 'Promo / Coupon Code'), ('LOYALTY', 'Loyalty / Reward Points'), ('VOLUME', 'Bulk / Volume Discount'), ('CUSTOM', 'Other / Custom Offer')], default='CUSTOM', help_text='Underlying core category behavior', max_length=20)),
                ('code', models.CharField(blank=True, help_text='Coupon code if applicable', max_length=50, null=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_categories', to='invoices.firm')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Black Friday 20% Off', max_length=100)),
                ('applied_code', models.CharField(blank=True, help_text='Coupon code if applicable', max_length=50, null=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Based (%)'), ('FLAT', 'Flat Amount Deduction ($)')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_category', to='invoices.invoice')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_category', to='invoices.discountcategory')),
            ],
        ),
    ]
