# Generated by Django 6.0.5 on 2026-06-05 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_discountcategory_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcategory',
            name='value',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
