# Generated by Django 6.0.5 on 2026-06-11 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_discountcategory_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='per_item_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
